version: "3.9"
services:
  scan:
    build: ../packages/scan
    volumes:
      - ../packages/scan:/app
    # entrypoint: ["sleep","999999999"]

  price:
    build: ../packages/price
    volumes:
      - ../packages/price:/app
  explorer:
    build: ../packages/next
    volumes:
      - ../packages/next:/app
    ports:
      - 6001:6001
    depends_on:
      - mongodb
      - scan
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGO_INITDB_DATABASE: statescan-statemine
    ports:
        - 27017:27017
