version: "3.9"
services:
  blockchain:
    build:
      context: ../../bholdus-chain
      dockerfile: Dockerfile.release
    command: bash -c "/usr/local/bin/bholdus --dev --ws-external"
    ports:
      - 9944:9944

  scan:
    build: ../packages/scan
    env_file: ../packages/scan/.env
    volumes:
      - ../packages/scan:/app
    depends_on:
      - mongodb

  price:
    build: ../packages/price
    volumes:
      - ../packages/price:/app
  explorer:
    build: ../packages/next
    volumes:
      - ../packages/next:/app
    ports:
      - 6001:6001
    depends_on:
      - scan
      - mongodb
  mongodb:
    build: ./mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: statescan-statemine
      MONGO_REPLICA_SET_NAME: "mongo-replica-0"
    volumes:
      - ../docker-data/mongodb/db:/data/db
      - ../docker-data/mongodb/log:/var/log/mongodb
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongodb:27017"
    ports:
      - 8081:8081
